apiVersion: v1
kind: PersistentVolume
metadata:
  name: inference-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: standard
  hostPath:
    path: /home/docker/inference_data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inference-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: inference-data-pv
  storageClassName: standard # Minikube 기본 StorageClass

