apiVersion: v1
kind: PersistentVolume
metadata:
  name: checkpoint-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: standard # Minikube 기본 StorageClass
  hostPath:
    path: /home/docker/checkpoints

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: checkpoint-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: checkpoint-pv 
  storageClassName: standard # Minikube 기본 StorageClass
