apiVersion: v1
kind: PersistentVolume
metadata:
  name: train-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: standard
  hostPath:
    path: /home/docker/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: train-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: train-data-pv
  storageClassName: standard

