apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: standard # Minikube 기본 StorageClass
  hostPath:
    path: /Users/aimmo-aiy-0297/Desktop/workspace/mlops/train_mnist/checkpoints

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: model-pv 
  storageClassName: standard # Minikube 기본 StorageClass
